<a href="https://colab.research.google.com/github/cromi0256/Study01/blob/main/11%EC%9E%A5_%EB%B9%84%EB%AA%A8%EC%88%98%EA%B2%80%EC%A0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#비모수 검정
#모수에 대한 가정 없이 검정
#모집단의 분포에 가정하지 않음
#집단의 분포가 정규분포가 아니거나, 표본의 크기가 작거나, 서열척도(또는 명목척도도인 경우 사용

In [2]:
import numpy as np
import scipy.stats as sp

#11-1 카이제곱 검정
#적합성 검정:관측값이 특정한 값이나 이론적 분포를 따르는지 검정
data1=np.array([400,440,380,350])
#H0=관측값은 서로 동일하다, H1=관측값은 차이가 있다
m0=data1.mean()
cstat,p = sp.chisquare(data1,m0)
print(f'검정통계량:{cstat}  (p-value:{p})')
#검정 결과 관측값은 서로 다른 분포에서 왔다

검정통계량:10.891719745222929  (p-value:0.01232603124556947)


In [3]:
#독립성 검정:한 모집단 내 두 인자의 관찰값이 서로 영향을 주는지 검정
import pandas as pd
data2=pd.DataFrame({'나이':['10대','30대'],'통과':[700,200],'실패':[300,100]}).set_index('나이')
print(data2)

      통과   실패
나이           
10대  700  300
30대  200  100


In [4]:
chi2,p,df,expec=sp.chi2_contingency(data2,correction=False)
print(f'검정통계량:{chi2} (p-value{p})')
#나이와 통과여부는 서로 독립임(귀무가설 채택)

검정통계량:1.2037037037037033 (p-value0.27258268190765333)


In [5]:
#동질성 검정:여러 모집단 간 수준에 대한 차이
#H0:모든 집단의 분포는 차이가 없다, H1:적어도 한 그룹은 분포 상 차이가 있다
data3=pd.DataFrame({'과목':['국어','영어','수학'],'A반':[80,70,60],
                    'B반':[55,60,50],'C반':[70,75,30]}).set_index('과목')
chi2,p,df,expec=sp.chi2_contingency(data3,correction=False)
print('기댓값',expec)
print(f'검정통계량:{chi2} (p-value{p})')

기댓값 [[78.27272727 61.5        65.22727273]
 [78.27272727 61.5        65.22727273]
 [53.45454545 42.         44.54545455]]
검정통계량:10.524307283889163 (p-value0.03246380561134725)


In [6]:
#일표본 Run검정
#H0:샘플은 무작위로 추출되었다  H1:샘플은 무작위로 추출되지 않았다
from statsmodels.sandbox.stats.runs import runstest_1samp
data4=['전진','전진','후진','중립','전진','중립','중립','중립','후진','전진','전진']
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data4=le.fit_transform(data4)
print(data4)
r1stat,p=runstest_1samp(data4,cutoff='median')
print(f'검정통계량:{r1stat} (p-value{p})')

[0 0 2 1 0 1 1 1 2 0 0]
검정통계량:-0.6123724356957942 (p-value0.54029137460742)


In [7]:
#이표본 Run검정
#H0:두 데이터는 같은 분포에서 왔다  H1:두 데이터는 다른 분포에서 왔다
from statsmodels.sandbox.stats.runs import runstest_2samp
np.random.seed(1234)
data5=[220,204,243,226,215,208,233,234]
data6=[230,999,222,217,236,238]
r2stat,p=runstest_2samp(data5,data6)
print(f'검정통계량:{r2stat} (p-value{p})')

검정통계량:0.9346671291301643 (p-value0.34995987200686984)


In [31]:
#11-3 이항변수 데이터 검정
#맥니머 검정:대응관계인 두 변수의 데이터 분포 차이 검정
data7=pd.DataFrame([[7,11],[16,35]],index=['전_긍정','전_부정'],columns=['후_긍정','후_부정'])
from statsmodels.stats.contingency_tables import mcnemar
result=mcnemar(data7.values,exact=False,correction=False)
print(data7)
print(result)

      후_긍정  후_부정
전_긍정     7    11
전_부정    16    35
pvalue      0.3359238131517329
statistic   0.9259259259259259


In [34]:
#코크란Q 검정:대응관계가 셋 이상인 데이터 분포 차이 검정
from statsmodels.stats.contingency_tables import cochrans_q

In [36]:
#11-4부호 순위 검정
#Wilcoxon 부호 순위 검정:단일 표본이나 대응관계인 두 서열척도의 표본 중앙값 비교
#scipy.stats.wilcoxon

#Wilcoxon 순위합 검정: 서열척도이며 서로 독립인 두 표본의 차이비교
#scipy.stats.[ranksums, mannwhitneyu]

In [35]:
#11-5 k표본 순위 데이터 검정
#크러스컬 윌리스 검정:세 변수 이상 대응관계가 없는 데이터 차이 검정(일원배치 분산분석의 비모수 검정)
#사후검정:윌콕슨 순위합검정
#scipy.stats.kruskal

In [37]:
#프리드먼 검정:세 변수 이상 대응관계가 있는 데이터 차이 검정
#사후검정:윌콕슨 부호순위검정
#scipy.stats.friedmanchisquare